name: 'Version File'
description: 'Create or update a version file during release using laminas automatic release'
branding:
  icon: tag
  color: blue
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/bump.sh
      shell: bash
